apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - image: httpd
    name: httpd-pod
    volumeMounts:
    - name: htdocs
      mountPath: "/usr/local/apache2/htdocs/"
    ports:
    - containerPort: 6789
      protocol: TCP
  volumes:
  - name: htdocs
    persistentVolumeClaim:
      claimName: httpd-example-pvc
