apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: http-go
  name: http-go
spec:
  serviceAccountName: http-go
  containers:
  - image: gasbugs/http-go:v3
    name: http-go
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
