apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-redis
  name: nginx-redis
spec:
  containers:
  - image: nginx
    name: mc-nginx
  - image: redis
    name: mc-redis
    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
